line-length = 100

[lint]
select = ["ALL"]
ignore = [
    "FBT",  # flake8-boolean-trap
    "N803",  # invalid-argument-name
    "PLR2004",  # magic-value-comparison
    "SIM300",  # yoda-conditions
]

[lint.per-file-ignores]
"noxfile.py" = [
    "D100",  # undocumented-public-module
]
"docs_src/**/*.py" = [
    "D",  # pydocstyle
    "INP001",  # implicit-namespace-package
]

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[lint.pydocstyle]
convention = "numpy"
